export const maneuverSpeeds = [0, 1, 2, 3, 4, 5];
export const maneuverColumns = ['A', 'E', 'L', 'T', 'B', 'F', 'S', 'N', 'Y', 'P', 'R', 'D', 'K', 'O'];
export const colorMapping = new Map([
    ["Red", "#f71d1d"],
    ["Blue", "#60a5ff"],
    ['White', 'white'],
    ["Green", '#61f973'],
    ['Yellow', '#f9f393']
]);
export const referenceMap = new Map([
    ['A', {direction: 'Left', type: 'Reverse Bank', faIconName: 'arrow-down', iconRotation: 'rotate(45deg)'}],
    ['E', {direction: "Left", type: "Tallon Roll", faIconName: 'arrow-left'}],
    ['L', {direction: "Left", type: "Segnor's Loop", faIconName: 'arrow-left'}],
    ['T', {direction: "Left", type: "Turn", faIconName: 'arrow-left'}],
    ['B', {direction: "Left", type: "Bank", faIconName: 'arrow-left', iconRotation: 'rotate(45deg)'}],
    ['F', {direction: null, type: "Straight", faIconName: 'arrow-up'}],
    ['S', {direction: null, type: "Reverse Straight", faIconName: 'arrow-down'}],
    ['N', {direction: "Right", type: "Bank", faIconName: 'arrow-up', iconRotation: 'rotate(45deg)'}],
    ['Y', {direction: "Right", type: "Turn", faIconName: 'arrow-right'}],
    ['P', {direction: "Right", type: "Segnor's Loop", faIconName: 'arrow-right'}],
    ['R', {direction: "Right", type: "Tallon Roll", faIconName: 'arrow-right'}],
    ['D', {direction: "Right", type: "Reverse Bank", faIconName: 'arrow-right', iconRotation: 'rotate(45deg)'}],
    ['K', {direction: null, type: "Koiogran Turn", faIconName: 'undo'}],
    ['O', {direction: null, type: "Stationary", faIconName: 'stop'}]
]);

export const ACTIVATION_PHASE_MAP = new Map([
    [0, 'next-ship'],
    [1, 'reveal-dial'],
    [2, 'execute-maneuver'],
    [3, 'perform-action'],
]);

export function buildPilot(pilotId, shipList){
    let ship = shipList.find(ship => ship.pilots.some(pilot => pilot.xws === pilotId));
    ship.pilots = [ship.pilots.find(pilot => pilot.xws === pilotId)];
    return ship;
}

export const VALID_ICONS = [
    'agility',
    'astromech',
    'attack',
    'bankleft',
    'bankright',
    'barrelroll',
    'base-all',
    'base-small',
    'base-medium',
    'base-large',
    'boost',
    'bullseyearc',
    'calculate',
    'cannon',
    'cargo',
    'charge',
    'cloak',
    'condition-outline',
    'condition',
    'config',
    'coordinate',
    'crew',
    'crit',
    'dalan-bankleft',
    'dalan-bankright',
    'device',
    'doubleturretarc',
    'empire',
    'energy',
    'epic',
    'evade',
    'firstorder',
    'focus',
    'forcecharge',
    'forcepower',
    'frontarc',
    'fullfrontarc',
    'fullreararc',
    'gunner',
    'hardpoint',
    'helmet-imperial',
    'helmet-rebel',
    'helmet-scum',
    'hit',
    'hull',
    'ig88d-sloopleft',
    'ig88d-sloopright',
    'illicit',
    'jam',
    'kturn',
    'leftarc',
    'linked',
    'lock',
    'missile',
    'modification',
    'obstacle-core2asteroid0-outline',
    'obstacle-core2asteroid0',
    'obstacle-core2asteroid1-outline',
    'obstacle-core2asteroid1',
    'obstacle-core2asteroid2-outline',
    'obstacle-core2asteroid2',
    'obstacle-core2asteroid3-outline',
    'obstacle-core2asteroid3',
    'obstacle-core2asteroid4-outline',
    'obstacle-core2asteroid4',
    'obstacle-core2asteroid5-outline',
    'obstacle-core2asteroid5',
    'obstacle-coreasteroid0-outline',
    'obstacle-coreasteroid0',
    'obstacle-coreasteroid1-outline',
    'obstacle-coreasteroid1',
    'obstacle-coreasteroid2-outline',
    'obstacle-coreasteroid2',
    'obstacle-coreasteroid3-outline',
    'obstacle-coreasteroid3',
    'obstacle-coreasteroid4-outline',
    'obstacle-coreasteroid4',
    'obstacle-coreasteroid5-outline',
    'obstacle-coreasteroid5',
    'obstacle-vt49decimatordebris0-outline',
    'obstacle-vt49decimatordebris0',
    'obstacle-vt49decimatordebris1-outline',
    'obstacle-vt49decimatordebris1',
    'obstacle-vt49decimatordebris2-outline',
    'obstacle-vt49decimatordebris2',
    'obstacle-yt2400debris0-outline',
    'obstacle-yt2400debris0',
    'obstacle-yt2400debris1-outline',
    'obstacle-yt2400debris1',
    'obstacle-yt2400debris2-outline',
    'obstacle-yt2400debris2',
    'rangebonusindicator',
    'reararc',
    'rebel-outline',
    'rebel',
    'recover',
    'recurring',
    'reinforce',
    'reload',
    'republic',
    'reversebankleft',
    'reversebankright',
    'reversestraight',
    'rightarc',
    'rotatearc',
    'scum',
    'separatists',
    'sensor',
    'shield',
    'singleturretarc',
    'slam',
    'sloopleft',
    'sloopright',
    'squad-point-cost',
    'stop',
    'straight',
    'talent',
    'team',
    'tech',
    'title',
    'token-calculate-outline',
    'token-calculate',
    'token-charge-outline',
    'token-charge',
    'token-crit-outline',
    'token-crit',
    'token-cloak-outline',
    'token-cloak',
    'token-evade-outline',
    'token-evade',
    'token-focus-outline',
    'token-focus',
    'token-force-outline',
    'token-force',
    'token-disarm-outline',
    'token-disarm',
    'token-ion-outline',
    'token-ion',
    'token-jam-outline',
    'token-jam',
    'token-lock-outline',
    'token-lock',
    'token-reinforce-outline',
    'token-reinforce',
    'token-reinforceaft-outline',
    'token-reinforceaft',
    'token-shield-outline',
    'token-shield',
    'token-stress-outline',
    'token-stress',
    'token-tractor-outline',
    'token-tractor',
    'torpedo',
    'trollleft',
    'trollright',
    'turnleft',
    'turnright',
    'turret',
    'unique-outline',
    'unique'
];
export const SHIP_ICONS = [
    'aggressorassaultfighter',
    'alphaclassstarwing',
    'arc170starfighter',
    'asf01bwing',
    'attackshuttle',
    'auzituckgunship',
    'btla4ywing',
    'btls8kwing',
    'cr90corvette',
    'croccruiser',
    'customizedyt1300lightfreighter',
    'escapecraft',
    'ewing',
    'fangfighter',
    'firesprayclasspatrolcraft',
    'g1astarfighter',
    'gozanticlasscruiser',
    'gr75mediumtransport',
    'hwk290lightfreighter',
    'jumpmaster5000',
    'kihraxzfighter',
    'lambdaclasst4ashuttle',
    'lancerclasspursuitcraft',
    'm12lkimogilafighter',
    'm3ainterceptor',
    'mg100starfortresssf17',
    'modifiedyt1300lightfreighter',
    'quadrijettransferspacetug',
    'raiderclasscorvette',
    'rz1awing',
    'scurrgh6bomber',
    'sheathipedeclassshuttle',
    'starviperclassattackplatform',
    't65xwing',
    't70xwing',
    'tieadvancedv1',
    'tieadvancedx1',
    'tieagaggressor',
    'tiecapunisher',
    'tieddefender',
    'tiefofighter',
    'tieinterceptor',
    'tielnfighter',
    'tiephphantom',
    'tiereaper',
    'tiesabomber',
    'tiesffighter',
    'tiesilencer',
    'tieskstriker',
    'upsilonclassshuttle',
    'ut60duwing',
    'vcx100lightfreighter',
    'vt49decimator',
    'yt2400lightfreighter',
    'yv666lightfreighter',
    'z95af4headhunter'
];